package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPrintJobTimeTotalReader is a Reader for the GetPrintJobTimeTotal structure.
type GetPrintJobTimeTotalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrintJobTimeTotalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrintJobTimeTotalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrintJobTimeTotalOK creates a GetPrintJobTimeTotalOK with default headers values
func NewGetPrintJobTimeTotalOK() *GetPrintJobTimeTotalOK {
	return &GetPrintJobTimeTotalOK{}
}

/*GetPrintJobTimeTotalOK handles this case with default header values.

GetPrintJobTimeTotalOK get print job time total o k
*/
type GetPrintJobTimeTotalOK struct {
	Payload int64
}

func (o *GetPrintJobTimeTotalOK) Error() string {
	return fmt.Sprintf("[GET /print_job/time_total][%d] getPrintJobTimeTotalOK  %+v", 200, o.Payload)
}

func (o *GetPrintJobTimeTotalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
