package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrintJobReader is a Reader for the GetPrintJob structure.
type GetPrintJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrintJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrintJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrintJobOK creates a GetPrintJobOK with default headers values
func NewGetPrintJobOK() *GetPrintJobOK {
	return &GetPrintJobOK{}
}

/*GetPrintJobOK handles this case with default header values.

Print job object
*/
type GetPrintJobOK struct {
	Payload *models.PrintJob
}

func (o *GetPrintJobOK) Error() string {
	return fmt.Sprintf("[GET /print_job][%d] getPrintJobOK  %+v", 200, o.Payload)
}

func (o *GetPrintJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PrintJob)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
