package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrintJobStateParams creates a new GetPrintJobStateParams object
// with the default values initialized.
func NewGetPrintJobStateParams() *GetPrintJobStateParams {

	return &GetPrintJobStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrintJobStateParamsWithTimeout creates a new GetPrintJobStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrintJobStateParamsWithTimeout(timeout time.Duration) *GetPrintJobStateParams {

	return &GetPrintJobStateParams{

		timeout: timeout,
	}
}

// NewGetPrintJobStateParamsWithContext creates a new GetPrintJobStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrintJobStateParamsWithContext(ctx context.Context) *GetPrintJobStateParams {

	return &GetPrintJobStateParams{

		Context: ctx,
	}
}

// NewGetPrintJobStateParamsWithHTTPClient creates a new GetPrintJobStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrintJobStateParamsWithHTTPClient(client *http.Client) *GetPrintJobStateParams {

	return &GetPrintJobStateParams{
		HTTPClient: client,
	}
}

/*GetPrintJobStateParams contains all the parameters to send to the API endpoint
for the get print job state operation typically these are written to a http.Request
*/
type GetPrintJobStateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get print job state params
func (o *GetPrintJobStateParams) WithTimeout(timeout time.Duration) *GetPrintJobStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get print job state params
func (o *GetPrintJobStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get print job state params
func (o *GetPrintJobStateParams) WithContext(ctx context.Context) *GetPrintJobStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get print job state params
func (o *GetPrintJobStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get print job state params
func (o *GetPrintJobStateParams) WithHTTPClient(client *http.Client) *GetPrintJobStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get print job state params
func (o *GetPrintJobStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrintJobStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
