package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrintJobProgressParams creates a new GetPrintJobProgressParams object
// with the default values initialized.
func NewGetPrintJobProgressParams() *GetPrintJobProgressParams {

	return &GetPrintJobProgressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrintJobProgressParamsWithTimeout creates a new GetPrintJobProgressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrintJobProgressParamsWithTimeout(timeout time.Duration) *GetPrintJobProgressParams {

	return &GetPrintJobProgressParams{

		timeout: timeout,
	}
}

// NewGetPrintJobProgressParamsWithContext creates a new GetPrintJobProgressParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrintJobProgressParamsWithContext(ctx context.Context) *GetPrintJobProgressParams {

	return &GetPrintJobProgressParams{

		Context: ctx,
	}
}

// NewGetPrintJobProgressParamsWithHTTPClient creates a new GetPrintJobProgressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrintJobProgressParamsWithHTTPClient(client *http.Client) *GetPrintJobProgressParams {

	return &GetPrintJobProgressParams{
		HTTPClient: client,
	}
}

/*GetPrintJobProgressParams contains all the parameters to send to the API endpoint
for the get print job progress operation typically these are written to a http.Request
*/
type GetPrintJobProgressParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get print job progress params
func (o *GetPrintJobProgressParams) WithTimeout(timeout time.Duration) *GetPrintJobProgressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get print job progress params
func (o *GetPrintJobProgressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get print job progress params
func (o *GetPrintJobProgressParams) WithContext(ctx context.Context) *GetPrintJobProgressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get print job progress params
func (o *GetPrintJobProgressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get print job progress params
func (o *GetPrintJobProgressParams) WithHTTPClient(client *http.Client) *GetPrintJobProgressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get print job progress params
func (o *GetPrintJobProgressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrintJobProgressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
