package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrintJobParams creates a new GetPrintJobParams object
// with the default values initialized.
func NewGetPrintJobParams() *GetPrintJobParams {

	return &GetPrintJobParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrintJobParamsWithTimeout creates a new GetPrintJobParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrintJobParamsWithTimeout(timeout time.Duration) *GetPrintJobParams {

	return &GetPrintJobParams{

		timeout: timeout,
	}
}

// NewGetPrintJobParamsWithContext creates a new GetPrintJobParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrintJobParamsWithContext(ctx context.Context) *GetPrintJobParams {

	return &GetPrintJobParams{

		Context: ctx,
	}
}

// NewGetPrintJobParamsWithHTTPClient creates a new GetPrintJobParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrintJobParamsWithHTTPClient(client *http.Client) *GetPrintJobParams {

	return &GetPrintJobParams{
		HTTPClient: client,
	}
}

/*GetPrintJobParams contains all the parameters to send to the API endpoint
for the get print job operation typically these are written to a http.Request
*/
type GetPrintJobParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get print job params
func (o *GetPrintJobParams) WithTimeout(timeout time.Duration) *GetPrintJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get print job params
func (o *GetPrintJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get print job params
func (o *GetPrintJobParams) WithContext(ctx context.Context) *GetPrintJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get print job params
func (o *GetPrintJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get print job params
func (o *GetPrintJobParams) WithHTTPClient(client *http.Client) *GetPrintJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get print job params
func (o *GetPrintJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrintJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
