package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrintJobSourceUserParams creates a new GetPrintJobSourceUserParams object
// with the default values initialized.
func NewGetPrintJobSourceUserParams() *GetPrintJobSourceUserParams {

	return &GetPrintJobSourceUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrintJobSourceUserParamsWithTimeout creates a new GetPrintJobSourceUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrintJobSourceUserParamsWithTimeout(timeout time.Duration) *GetPrintJobSourceUserParams {

	return &GetPrintJobSourceUserParams{

		timeout: timeout,
	}
}

// NewGetPrintJobSourceUserParamsWithContext creates a new GetPrintJobSourceUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrintJobSourceUserParamsWithContext(ctx context.Context) *GetPrintJobSourceUserParams {

	return &GetPrintJobSourceUserParams{

		Context: ctx,
	}
}

// NewGetPrintJobSourceUserParamsWithHTTPClient creates a new GetPrintJobSourceUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrintJobSourceUserParamsWithHTTPClient(client *http.Client) *GetPrintJobSourceUserParams {

	return &GetPrintJobSourceUserParams{
		HTTPClient: client,
	}
}

/*GetPrintJobSourceUserParams contains all the parameters to send to the API endpoint
for the get print job source user operation typically these are written to a http.Request
*/
type GetPrintJobSourceUserParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get print job source user params
func (o *GetPrintJobSourceUserParams) WithTimeout(timeout time.Duration) *GetPrintJobSourceUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get print job source user params
func (o *GetPrintJobSourceUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get print job source user params
func (o *GetPrintJobSourceUserParams) WithContext(ctx context.Context) *GetPrintJobSourceUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get print job source user params
func (o *GetPrintJobSourceUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get print job source user params
func (o *GetPrintJobSourceUserParams) WithHTTPClient(client *http.Client) *GetPrintJobSourceUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get print job source user params
func (o *GetPrintJobSourceUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrintJobSourceUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
