package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrintJobSourceApplicationParams creates a new GetPrintJobSourceApplicationParams object
// with the default values initialized.
func NewGetPrintJobSourceApplicationParams() *GetPrintJobSourceApplicationParams {

	return &GetPrintJobSourceApplicationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrintJobSourceApplicationParamsWithTimeout creates a new GetPrintJobSourceApplicationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrintJobSourceApplicationParamsWithTimeout(timeout time.Duration) *GetPrintJobSourceApplicationParams {

	return &GetPrintJobSourceApplicationParams{

		timeout: timeout,
	}
}

// NewGetPrintJobSourceApplicationParamsWithContext creates a new GetPrintJobSourceApplicationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrintJobSourceApplicationParamsWithContext(ctx context.Context) *GetPrintJobSourceApplicationParams {

	return &GetPrintJobSourceApplicationParams{

		Context: ctx,
	}
}

// NewGetPrintJobSourceApplicationParamsWithHTTPClient creates a new GetPrintJobSourceApplicationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrintJobSourceApplicationParamsWithHTTPClient(client *http.Client) *GetPrintJobSourceApplicationParams {

	return &GetPrintJobSourceApplicationParams{
		HTTPClient: client,
	}
}

/*GetPrintJobSourceApplicationParams contains all the parameters to send to the API endpoint
for the get print job source application operation typically these are written to a http.Request
*/
type GetPrintJobSourceApplicationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get print job source application params
func (o *GetPrintJobSourceApplicationParams) WithTimeout(timeout time.Duration) *GetPrintJobSourceApplicationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get print job source application params
func (o *GetPrintJobSourceApplicationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get print job source application params
func (o *GetPrintJobSourceApplicationParams) WithContext(ctx context.Context) *GetPrintJobSourceApplicationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get print job source application params
func (o *GetPrintJobSourceApplicationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get print job source application params
func (o *GetPrintJobSourceApplicationParams) WithHTTPClient(client *http.Client) *GetPrintJobSourceApplicationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get print job source application params
func (o *GetPrintJobSourceApplicationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrintJobSourceApplicationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
