package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPrintJobStateReader is a Reader for the GetPrintJobState structure.
type GetPrintJobStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrintJobStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrintJobStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrintJobStateOK creates a GetPrintJobStateOK with default headers values
func NewGetPrintJobStateOK() *GetPrintJobStateOK {
	return &GetPrintJobStateOK{}
}

/*GetPrintJobStateOK handles this case with default header values.

GetPrintJobStateOK get print job state o k
*/
type GetPrintJobStateOK struct {
	Payload string
}

func (o *GetPrintJobStateOK) Error() string {
	return fmt.Sprintf("[GET /print_job/state][%d] getPrintJobStateOK  %+v", 200, o.Payload)
}

func (o *GetPrintJobStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
