package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPrintJobTimeElapsedReader is a Reader for the GetPrintJobTimeElapsed structure.
type GetPrintJobTimeElapsedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrintJobTimeElapsedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrintJobTimeElapsedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrintJobTimeElapsedOK creates a GetPrintJobTimeElapsedOK with default headers values
func NewGetPrintJobTimeElapsedOK() *GetPrintJobTimeElapsedOK {
	return &GetPrintJobTimeElapsedOK{}
}

/*GetPrintJobTimeElapsedOK handles this case with default header values.

GetPrintJobTimeElapsedOK get print job time elapsed o k
*/
type GetPrintJobTimeElapsedOK struct {
	Payload int64
}

func (o *GetPrintJobTimeElapsedOK) Error() string {
	return fmt.Sprintf("[GET /print_job/time_elapsed][%d] getPrintJobTimeElapsedOK  %+v", 200, o.Payload)
}

func (o *GetPrintJobTimeElapsedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
