package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrintJobUUIDParams creates a new GetPrintJobUUIDParams object
// with the default values initialized.
func NewGetPrintJobUUIDParams() *GetPrintJobUUIDParams {

	return &GetPrintJobUUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrintJobUUIDParamsWithTimeout creates a new GetPrintJobUUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrintJobUUIDParamsWithTimeout(timeout time.Duration) *GetPrintJobUUIDParams {

	return &GetPrintJobUUIDParams{

		timeout: timeout,
	}
}

// NewGetPrintJobUUIDParamsWithContext creates a new GetPrintJobUUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrintJobUUIDParamsWithContext(ctx context.Context) *GetPrintJobUUIDParams {

	return &GetPrintJobUUIDParams{

		Context: ctx,
	}
}

// NewGetPrintJobUUIDParamsWithHTTPClient creates a new GetPrintJobUUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrintJobUUIDParamsWithHTTPClient(client *http.Client) *GetPrintJobUUIDParams {

	return &GetPrintJobUUIDParams{
		HTTPClient: client,
	}
}

/*GetPrintJobUUIDParams contains all the parameters to send to the API endpoint
for the get print job UUID operation typically these are written to a http.Request
*/
type GetPrintJobUUIDParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get print job UUID params
func (o *GetPrintJobUUIDParams) WithTimeout(timeout time.Duration) *GetPrintJobUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get print job UUID params
func (o *GetPrintJobUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get print job UUID params
func (o *GetPrintJobUUIDParams) WithContext(ctx context.Context) *GetPrintJobUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get print job UUID params
func (o *GetPrintJobUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get print job UUID params
func (o *GetPrintJobUUIDParams) WithHTTPClient(client *http.Client) *GetPrintJobUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get print job UUID params
func (o *GetPrintJobUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrintJobUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
