package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPrintJobNameReader is a Reader for the GetPrintJobName structure.
type GetPrintJobNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrintJobNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrintJobNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrintJobNameOK creates a GetPrintJobNameOK with default headers values
func NewGetPrintJobNameOK() *GetPrintJobNameOK {
	return &GetPrintJobNameOK{}
}

/*GetPrintJobNameOK handles this case with default header values.

Name of print job
*/
type GetPrintJobNameOK struct {
	Payload string
}

func (o *GetPrintJobNameOK) Error() string {
	return fmt.Sprintf("[GET /print_job/name][%d] getPrintJobNameOK  %+v", 200, o.Payload)
}

func (o *GetPrintJobNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
