package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrintJobNameParams creates a new GetPrintJobNameParams object
// with the default values initialized.
func NewGetPrintJobNameParams() *GetPrintJobNameParams {

	return &GetPrintJobNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrintJobNameParamsWithTimeout creates a new GetPrintJobNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrintJobNameParamsWithTimeout(timeout time.Duration) *GetPrintJobNameParams {

	return &GetPrintJobNameParams{

		timeout: timeout,
	}
}

// NewGetPrintJobNameParamsWithContext creates a new GetPrintJobNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrintJobNameParamsWithContext(ctx context.Context) *GetPrintJobNameParams {

	return &GetPrintJobNameParams{

		Context: ctx,
	}
}

// NewGetPrintJobNameParamsWithHTTPClient creates a new GetPrintJobNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrintJobNameParamsWithHTTPClient(client *http.Client) *GetPrintJobNameParams {

	return &GetPrintJobNameParams{
		HTTPClient: client,
	}
}

/*GetPrintJobNameParams contains all the parameters to send to the API endpoint
for the get print job name operation typically these are written to a http.Request
*/
type GetPrintJobNameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get print job name params
func (o *GetPrintJobNameParams) WithTimeout(timeout time.Duration) *GetPrintJobNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get print job name params
func (o *GetPrintJobNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get print job name params
func (o *GetPrintJobNameParams) WithContext(ctx context.Context) *GetPrintJobNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get print job name params
func (o *GetPrintJobNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get print job name params
func (o *GetPrintJobNameParams) WithHTTPClient(client *http.Client) *GetPrintJobNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get print job name params
func (o *GetPrintJobNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrintJobNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
