package print_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutPrintJobStateReader is a Reader for the PutPrintJobState structure.
type PutPrintJobStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPrintJobStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutPrintJobStateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutPrintJobStateNoContent creates a PutPrintJobStateNoContent with default headers values
func NewPutPrintJobStateNoContent() *PutPrintJobStateNoContent {
	return &PutPrintJobStateNoContent{}
}

/*PutPrintJobStateNoContent handles this case with default header values.

State changed
*/
type PutPrintJobStateNoContent struct {
}

func (o *PutPrintJobStateNoContent) Error() string {
	return fmt.Sprintf("[PUT /print_job/state][%d] putPrintJobStateNoContent ", 204)
}

func (o *PutPrintJobStateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
