package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuthCheckIDParams creates a new GetAuthCheckIDParams object
// with the default values initialized.
func NewGetAuthCheckIDParams() *GetAuthCheckIDParams {
	var ()
	return &GetAuthCheckIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthCheckIDParamsWithTimeout creates a new GetAuthCheckIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthCheckIDParamsWithTimeout(timeout time.Duration) *GetAuthCheckIDParams {
	var ()
	return &GetAuthCheckIDParams{

		timeout: timeout,
	}
}

// NewGetAuthCheckIDParamsWithContext creates a new GetAuthCheckIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthCheckIDParamsWithContext(ctx context.Context) *GetAuthCheckIDParams {
	var ()
	return &GetAuthCheckIDParams{

		Context: ctx,
	}
}

// NewGetAuthCheckIDParamsWithHTTPClient creates a new GetAuthCheckIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthCheckIDParamsWithHTTPClient(client *http.Client) *GetAuthCheckIDParams {
	var ()
	return &GetAuthCheckIDParams{
		HTTPClient: client,
	}
}

/*GetAuthCheckIDParams contains all the parameters to send to the API endpoint
for the get auth check ID operation typically these are written to a http.Request
*/
type GetAuthCheckIDParams struct {

	/*ID
	  id returned from the /auth/request call

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth check ID params
func (o *GetAuthCheckIDParams) WithTimeout(timeout time.Duration) *GetAuthCheckIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth check ID params
func (o *GetAuthCheckIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth check ID params
func (o *GetAuthCheckIDParams) WithContext(ctx context.Context) *GetAuthCheckIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth check ID params
func (o *GetAuthCheckIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth check ID params
func (o *GetAuthCheckIDParams) WithHTTPClient(client *http.Client) *GetAuthCheckIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth check ID params
func (o *GetAuthCheckIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get auth check ID params
func (o *GetAuthCheckIDParams) WithID(id string) *GetAuthCheckIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get auth check ID params
func (o *GetAuthCheckIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthCheckIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
