package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAuthVerifyParams creates a new GetAuthVerifyParams object
// with the default values initialized.
func NewGetAuthVerifyParams() *GetAuthVerifyParams {

	return &GetAuthVerifyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthVerifyParamsWithTimeout creates a new GetAuthVerifyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAuthVerifyParamsWithTimeout(timeout time.Duration) *GetAuthVerifyParams {

	return &GetAuthVerifyParams{

		timeout: timeout,
	}
}

// NewGetAuthVerifyParamsWithContext creates a new GetAuthVerifyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAuthVerifyParamsWithContext(ctx context.Context) *GetAuthVerifyParams {

	return &GetAuthVerifyParams{

		Context: ctx,
	}
}

// NewGetAuthVerifyParamsWithHTTPClient creates a new GetAuthVerifyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAuthVerifyParamsWithHTTPClient(client *http.Client) *GetAuthVerifyParams {

	return &GetAuthVerifyParams{
		HTTPClient: client,
	}
}

/*GetAuthVerifyParams contains all the parameters to send to the API endpoint
for the get auth verify operation typically these are written to a http.Request
*/
type GetAuthVerifyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get auth verify params
func (o *GetAuthVerifyParams) WithTimeout(timeout time.Duration) *GetAuthVerifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth verify params
func (o *GetAuthVerifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth verify params
func (o *GetAuthVerifyParams) WithContext(ctx context.Context) *GetAuthVerifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth verify params
func (o *GetAuthVerifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth verify params
func (o *GetAuthVerifyParams) WithHTTPClient(client *http.Client) *GetAuthVerifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth verify params
func (o *GetAuthVerifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthVerifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
