package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHistoryPrintJobsParams creates a new GetHistoryPrintJobsParams object
// with the default values initialized.
func NewGetHistoryPrintJobsParams() *GetHistoryPrintJobsParams {
	var ()
	return &GetHistoryPrintJobsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHistoryPrintJobsParamsWithTimeout creates a new GetHistoryPrintJobsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHistoryPrintJobsParamsWithTimeout(timeout time.Duration) *GetHistoryPrintJobsParams {
	var ()
	return &GetHistoryPrintJobsParams{

		timeout: timeout,
	}
}

// NewGetHistoryPrintJobsParamsWithContext creates a new GetHistoryPrintJobsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHistoryPrintJobsParamsWithContext(ctx context.Context) *GetHistoryPrintJobsParams {
	var ()
	return &GetHistoryPrintJobsParams{

		Context: ctx,
	}
}

// NewGetHistoryPrintJobsParamsWithHTTPClient creates a new GetHistoryPrintJobsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHistoryPrintJobsParamsWithHTTPClient(client *http.Client) *GetHistoryPrintJobsParams {
	var ()
	return &GetHistoryPrintJobsParams{
		HTTPClient: client,
	}
}

/*GetHistoryPrintJobsParams contains all the parameters to send to the API endpoint
for the get history print jobs operation typically these are written to a http.Request
*/
type GetHistoryPrintJobsParams struct {

	/*Count
	  Allow a count parameter to specify the number of jobs to get from the log. Defaults to 50

	*/
	Count *float64
	/*Offset
	  Allow a offset parameter to specify the start in the history to get jobs from. Defaults to 0

	*/
	Offset *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get history print jobs params
func (o *GetHistoryPrintJobsParams) WithTimeout(timeout time.Duration) *GetHistoryPrintJobsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get history print jobs params
func (o *GetHistoryPrintJobsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get history print jobs params
func (o *GetHistoryPrintJobsParams) WithContext(ctx context.Context) *GetHistoryPrintJobsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get history print jobs params
func (o *GetHistoryPrintJobsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get history print jobs params
func (o *GetHistoryPrintJobsParams) WithHTTPClient(client *http.Client) *GetHistoryPrintJobsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get history print jobs params
func (o *GetHistoryPrintJobsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get history print jobs params
func (o *GetHistoryPrintJobsParams) WithCount(count *float64) *GetHistoryPrintJobsParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get history print jobs params
func (o *GetHistoryPrintJobsParams) SetCount(count *float64) {
	o.Count = count
}

// WithOffset adds the offset to the get history print jobs params
func (o *GetHistoryPrintJobsParams) WithOffset(offset *float64) *GetHistoryPrintJobsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get history print jobs params
func (o *GetHistoryPrintJobsParams) SetOffset(offset *float64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetHistoryPrintJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount float64
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatFloat64(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset float64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatFloat64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
