package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetHistoryPrintJobsReader is a Reader for the GetHistoryPrintJobs structure.
type GetHistoryPrintJobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHistoryPrintJobsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetHistoryPrintJobsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetHistoryPrintJobsOK creates a GetHistoryPrintJobsOK with default headers values
func NewGetHistoryPrintJobsOK() *GetHistoryPrintJobsOK {
	return &GetHistoryPrintJobsOK{}
}

/*GetHistoryPrintJobsOK handles this case with default header values.

All past PrintJobs on this printer
*/
type GetHistoryPrintJobsOK struct {
	Payload []*models.PrintJobHistory
}

func (o *GetHistoryPrintJobsOK) Error() string {
	return fmt.Sprintf("[GET /history/print_jobs][%d] getHistoryPrintJobsOK  %+v", 200, o.Payload)
}

func (o *GetHistoryPrintJobsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
