package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetHistoryPrintJobsUUIDReader is a Reader for the GetHistoryPrintJobsUUID structure.
type GetHistoryPrintJobsUUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHistoryPrintJobsUUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetHistoryPrintJobsUUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetHistoryPrintJobsUUIDOK creates a GetHistoryPrintJobsUUIDOK with default headers values
func NewGetHistoryPrintJobsUUIDOK() *GetHistoryPrintJobsUUIDOK {
	return &GetHistoryPrintJobsUUIDOK{}
}

/*GetHistoryPrintJobsUUIDOK handles this case with default header values.

PrintJob with the given UUID
*/
type GetHistoryPrintJobsUUIDOK struct {
	Payload *models.PrintJobHistory
}

func (o *GetHistoryPrintJobsUUIDOK) Error() string {
	return fmt.Sprintf("[GET /history/print_jobs/{uuid}][%d] getHistoryPrintJobsUuidOK  %+v", 200, o.Payload)
}

func (o *GetHistoryPrintJobsUUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PrintJobHistory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
