package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new history API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for history API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetHistoryEvents get history events API
*/
func (a *Client) GetHistoryEvents(params *GetHistoryEventsParams) (*GetHistoryEventsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetHistoryEventsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetHistoryEvents",
		Method:             "GET",
		PathPattern:        "/history/events",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetHistoryEventsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetHistoryEventsOK), nil

}

/*
GetHistoryPrintJobs get history print jobs API
*/
func (a *Client) GetHistoryPrintJobs(params *GetHistoryPrintJobsParams) (*GetHistoryPrintJobsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetHistoryPrintJobsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetHistoryPrintJobs",
		Method:             "GET",
		PathPattern:        "/history/print_jobs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetHistoryPrintJobsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetHistoryPrintJobsOK), nil

}

/*
GetHistoryPrintJobsUUID get history print jobs UUID API
*/
func (a *Client) GetHistoryPrintJobsUUID(params *GetHistoryPrintJobsUUIDParams) (*GetHistoryPrintJobsUUIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetHistoryPrintJobsUUIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetHistoryPrintJobsUUID",
		Method:             "GET",
		PathPattern:        "/history/print_jobs/{uuid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetHistoryPrintJobsUUIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetHistoryPrintJobsUUIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
