package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSystemHardwareRevisionParams creates a new GetSystemHardwareRevisionParams object
// with the default values initialized.
func NewGetSystemHardwareRevisionParams() *GetSystemHardwareRevisionParams {

	return &GetSystemHardwareRevisionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemHardwareRevisionParamsWithTimeout creates a new GetSystemHardwareRevisionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSystemHardwareRevisionParamsWithTimeout(timeout time.Duration) *GetSystemHardwareRevisionParams {

	return &GetSystemHardwareRevisionParams{

		timeout: timeout,
	}
}

// NewGetSystemHardwareRevisionParamsWithContext creates a new GetSystemHardwareRevisionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSystemHardwareRevisionParamsWithContext(ctx context.Context) *GetSystemHardwareRevisionParams {

	return &GetSystemHardwareRevisionParams{

		Context: ctx,
	}
}

// NewGetSystemHardwareRevisionParamsWithHTTPClient creates a new GetSystemHardwareRevisionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSystemHardwareRevisionParamsWithHTTPClient(client *http.Client) *GetSystemHardwareRevisionParams {

	return &GetSystemHardwareRevisionParams{
		HTTPClient: client,
	}
}

/*GetSystemHardwareRevisionParams contains all the parameters to send to the API endpoint
for the get system hardware revision operation typically these are written to a http.Request
*/
type GetSystemHardwareRevisionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get system hardware revision params
func (o *GetSystemHardwareRevisionParams) WithTimeout(timeout time.Duration) *GetSystemHardwareRevisionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system hardware revision params
func (o *GetSystemHardwareRevisionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system hardware revision params
func (o *GetSystemHardwareRevisionParams) WithContext(ctx context.Context) *GetSystemHardwareRevisionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system hardware revision params
func (o *GetSystemHardwareRevisionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system hardware revision params
func (o *GetSystemHardwareRevisionParams) WithHTTPClient(client *http.Client) *GetSystemHardwareRevisionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system hardware revision params
func (o *GetSystemHardwareRevisionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemHardwareRevisionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
