package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSystemLanguageReader is a Reader for the GetSystemLanguage structure.
type GetSystemLanguageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemLanguageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSystemLanguageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemLanguageOK creates a GetSystemLanguageOK with default headers values
func NewGetSystemLanguageOK() *GetSystemLanguageOK {
	return &GetSystemLanguageOK{}
}

/*GetSystemLanguageOK handles this case with default header values.

Language
*/
type GetSystemLanguageOK struct {
	Payload string
}

func (o *GetSystemLanguageOK) Error() string {
	return fmt.Sprintf("[GET /system/language][%d] getSystemLanguageOK  %+v", 200, o.Payload)
}

func (o *GetSystemLanguageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
