package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSystemLanguageParams creates a new GetSystemLanguageParams object
// with the default values initialized.
func NewGetSystemLanguageParams() *GetSystemLanguageParams {

	return &GetSystemLanguageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemLanguageParamsWithTimeout creates a new GetSystemLanguageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSystemLanguageParamsWithTimeout(timeout time.Duration) *GetSystemLanguageParams {

	return &GetSystemLanguageParams{

		timeout: timeout,
	}
}

// NewGetSystemLanguageParamsWithContext creates a new GetSystemLanguageParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSystemLanguageParamsWithContext(ctx context.Context) *GetSystemLanguageParams {

	return &GetSystemLanguageParams{

		Context: ctx,
	}
}

// NewGetSystemLanguageParamsWithHTTPClient creates a new GetSystemLanguageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSystemLanguageParamsWithHTTPClient(client *http.Client) *GetSystemLanguageParams {

	return &GetSystemLanguageParams{
		HTTPClient: client,
	}
}

/*GetSystemLanguageParams contains all the parameters to send to the API endpoint
for the get system language operation typically these are written to a http.Request
*/
type GetSystemLanguageParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get system language params
func (o *GetSystemLanguageParams) WithTimeout(timeout time.Duration) *GetSystemLanguageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system language params
func (o *GetSystemLanguageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system language params
func (o *GetSystemLanguageParams) WithContext(ctx context.Context) *GetSystemLanguageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system language params
func (o *GetSystemLanguageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system language params
func (o *GetSystemLanguageParams) WithHTTPClient(client *http.Client) *GetSystemLanguageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system language params
func (o *GetSystemLanguageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemLanguageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
