package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSystemNameParams creates a new GetSystemNameParams object
// with the default values initialized.
func NewGetSystemNameParams() *GetSystemNameParams {

	return &GetSystemNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemNameParamsWithTimeout creates a new GetSystemNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSystemNameParamsWithTimeout(timeout time.Duration) *GetSystemNameParams {

	return &GetSystemNameParams{

		timeout: timeout,
	}
}

// NewGetSystemNameParamsWithContext creates a new GetSystemNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSystemNameParamsWithContext(ctx context.Context) *GetSystemNameParams {

	return &GetSystemNameParams{

		Context: ctx,
	}
}

// NewGetSystemNameParamsWithHTTPClient creates a new GetSystemNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSystemNameParamsWithHTTPClient(client *http.Client) *GetSystemNameParams {

	return &GetSystemNameParams{
		HTTPClient: client,
	}
}

/*GetSystemNameParams contains all the parameters to send to the API endpoint
for the get system name operation typically these are written to a http.Request
*/
type GetSystemNameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get system name params
func (o *GetSystemNameParams) WithTimeout(timeout time.Duration) *GetSystemNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system name params
func (o *GetSystemNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system name params
func (o *GetSystemNameParams) WithContext(ctx context.Context) *GetSystemNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system name params
func (o *GetSystemNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system name params
func (o *GetSystemNameParams) WithHTTPClient(client *http.Client) *GetSystemNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system name params
func (o *GetSystemNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
