package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSystemHardwareTypeidParams creates a new GetSystemHardwareTypeidParams object
// with the default values initialized.
func NewGetSystemHardwareTypeidParams() *GetSystemHardwareTypeidParams {

	return &GetSystemHardwareTypeidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemHardwareTypeidParamsWithTimeout creates a new GetSystemHardwareTypeidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSystemHardwareTypeidParamsWithTimeout(timeout time.Duration) *GetSystemHardwareTypeidParams {

	return &GetSystemHardwareTypeidParams{

		timeout: timeout,
	}
}

// NewGetSystemHardwareTypeidParamsWithContext creates a new GetSystemHardwareTypeidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSystemHardwareTypeidParamsWithContext(ctx context.Context) *GetSystemHardwareTypeidParams {

	return &GetSystemHardwareTypeidParams{

		Context: ctx,
	}
}

// NewGetSystemHardwareTypeidParamsWithHTTPClient creates a new GetSystemHardwareTypeidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSystemHardwareTypeidParamsWithHTTPClient(client *http.Client) *GetSystemHardwareTypeidParams {

	return &GetSystemHardwareTypeidParams{
		HTTPClient: client,
	}
}

/*GetSystemHardwareTypeidParams contains all the parameters to send to the API endpoint
for the get system hardware typeid operation typically these are written to a http.Request
*/
type GetSystemHardwareTypeidParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get system hardware typeid params
func (o *GetSystemHardwareTypeidParams) WithTimeout(timeout time.Duration) *GetSystemHardwareTypeidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system hardware typeid params
func (o *GetSystemHardwareTypeidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system hardware typeid params
func (o *GetSystemHardwareTypeidParams) WithContext(ctx context.Context) *GetSystemHardwareTypeidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system hardware typeid params
func (o *GetSystemHardwareTypeidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system hardware typeid params
func (o *GetSystemHardwareTypeidParams) WithHTTPClient(client *http.Client) *GetSystemHardwareTypeidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system hardware typeid params
func (o *GetSystemHardwareTypeidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemHardwareTypeidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
