package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSystemHardwareRevisionReader is a Reader for the GetSystemHardwareRevision structure.
type GetSystemHardwareRevisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemHardwareRevisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSystemHardwareRevisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemHardwareRevisionOK creates a GetSystemHardwareRevisionOK with default headers values
func NewGetSystemHardwareRevisionOK() *GetSystemHardwareRevisionOK {
	return &GetSystemHardwareRevisionOK{}
}

/*GetSystemHardwareRevisionOK handles this case with default header values.

Machine hardware revision
*/
type GetSystemHardwareRevisionOK struct {
	Payload int64
}

func (o *GetSystemHardwareRevisionOK) Error() string {
	return fmt.Sprintf("[GET /system/hardware/revision][%d] getSystemHardwareRevisionOK  %+v", 200, o.Payload)
}

func (o *GetSystemHardwareRevisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
