package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSystemCountryReader is a Reader for the GetSystemCountry structure.
type GetSystemCountryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemCountryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSystemCountryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemCountryOK creates a GetSystemCountryOK with default headers values
func NewGetSystemCountryOK() *GetSystemCountryOK {
	return &GetSystemCountryOK{}
}

/*GetSystemCountryOK handles this case with default header values.

country
*/
type GetSystemCountryOK struct {
	Payload string
}

func (o *GetSystemCountryOK) Error() string {
	return fmt.Sprintf("[GET /system/country][%d] getSystemCountryOK  %+v", 200, o.Payload)
}

func (o *GetSystemCountryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
