package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSystemVariantReader is a Reader for the GetSystemVariant structure.
type GetSystemVariantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemVariantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSystemVariantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemVariantOK creates a GetSystemVariantOK with default headers values
func NewGetSystemVariantOK() *GetSystemVariantOK {
	return &GetSystemVariantOK{}
}

/*GetSystemVariantOK handles this case with default header values.

Machine variant
*/
type GetSystemVariantOK struct {
	Payload string
}

func (o *GetSystemVariantOK) Error() string {
	return fmt.Sprintf("[GET /system/variant][%d] getSystemVariantOK  %+v", 200, o.Payload)
}

func (o *GetSystemVariantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
