package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutSystemCountryParams creates a new PutSystemCountryParams object
// with the default values initialized.
func NewPutSystemCountryParams() *PutSystemCountryParams {
	var ()
	return &PutSystemCountryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutSystemCountryParamsWithTimeout creates a new PutSystemCountryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutSystemCountryParamsWithTimeout(timeout time.Duration) *PutSystemCountryParams {
	var ()
	return &PutSystemCountryParams{

		timeout: timeout,
	}
}

// NewPutSystemCountryParamsWithContext creates a new PutSystemCountryParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutSystemCountryParamsWithContext(ctx context.Context) *PutSystemCountryParams {
	var ()
	return &PutSystemCountryParams{

		Context: ctx,
	}
}

// NewPutSystemCountryParamsWithHTTPClient creates a new PutSystemCountryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutSystemCountryParamsWithHTTPClient(client *http.Client) *PutSystemCountryParams {
	var ()
	return &PutSystemCountryParams{
		HTTPClient: client,
	}
}

/*PutSystemCountryParams contains all the parameters to send to the API endpoint
for the put system country operation typically these are written to a http.Request
*/
type PutSystemCountryParams struct {

	/*Country
	  Target country of system

	*/
	Country *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put system country params
func (o *PutSystemCountryParams) WithTimeout(timeout time.Duration) *PutSystemCountryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put system country params
func (o *PutSystemCountryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put system country params
func (o *PutSystemCountryParams) WithContext(ctx context.Context) *PutSystemCountryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put system country params
func (o *PutSystemCountryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put system country params
func (o *PutSystemCountryParams) WithHTTPClient(client *http.Client) *PutSystemCountryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put system country params
func (o *PutSystemCountryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCountry adds the country to the put system country params
func (o *PutSystemCountryParams) WithCountry(country *string) *PutSystemCountryParams {
	o.SetCountry(country)
	return o
}

// SetCountry adds the country to the put system country params
func (o *PutSystemCountryParams) SetCountry(country *string) {
	o.Country = country
}

// WriteToRequest writes these params to a swagger request
func (o *PutSystemCountryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Country); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
