package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutSystemNameParams creates a new PutSystemNameParams object
// with the default values initialized.
func NewPutSystemNameParams() *PutSystemNameParams {
	var ()
	return &PutSystemNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutSystemNameParamsWithTimeout creates a new PutSystemNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutSystemNameParamsWithTimeout(timeout time.Duration) *PutSystemNameParams {
	var ()
	return &PutSystemNameParams{

		timeout: timeout,
	}
}

// NewPutSystemNameParamsWithContext creates a new PutSystemNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutSystemNameParamsWithContext(ctx context.Context) *PutSystemNameParams {
	var ()
	return &PutSystemNameParams{

		Context: ctx,
	}
}

// NewPutSystemNameParamsWithHTTPClient creates a new PutSystemNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutSystemNameParamsWithHTTPClient(client *http.Client) *PutSystemNameParams {
	var ()
	return &PutSystemNameParams{
		HTTPClient: client,
	}
}

/*PutSystemNameParams contains all the parameters to send to the API endpoint
for the put system name operation typically these are written to a http.Request
*/
type PutSystemNameParams struct {

	/*Name
	  Target name of machine

	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put system name params
func (o *PutSystemNameParams) WithTimeout(timeout time.Duration) *PutSystemNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put system name params
func (o *PutSystemNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put system name params
func (o *PutSystemNameParams) WithContext(ctx context.Context) *PutSystemNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put system name params
func (o *PutSystemNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put system name params
func (o *PutSystemNameParams) WithHTTPClient(client *http.Client) *PutSystemNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put system name params
func (o *PutSystemNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the put system name params
func (o *PutSystemNameParams) WithName(name *string) *PutSystemNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put system name params
func (o *PutSystemNameParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PutSystemNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
