package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Bed (heated) bed of the printer
// swagger:model Bed
type Bed struct {

	// temperature
	Temperature *CurrentTargetNumberPair `json:"temperature,omitempty"`
}

// Validate validates this bed
func (m *Bed) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTemperature(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Bed) validateTemperature(formats strfmt.Registry) error {

	if swag.IsZero(m.Temperature) { // not required
		return nil
	}

	if m.Temperature != nil {

		if err := m.Temperature.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("temperature")
			}
			return err
		}
	}

	return nil
}
