package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Camera camera
// swagger:model Camera
type Camera struct {

	// feed
	// Required: true
	Feed *string `json:"feed"`
}

// Validate validates this camera
func (m *Camera) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeed(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Camera) validateFeed(formats strfmt.Registry) error {

	if err := validate.Required("feed", "body", m.Feed); err != nil {
		return err
	}

	return nil
}
