package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// CurrentTargetNumberPair Object with two numbers; Current (numeric) value of a setting and the target (numeric) value of a setting
// swagger:model CurrentTargetNumberPair
type CurrentTargetNumberPair struct {

	// current
	Current float64 `json:"current,omitempty"`

	// target
	Target float64 `json:"target,omitempty"`
}

// Validate validates this current target number pair
func (m *CurrentTargetNumberPair) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
