package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EventHistoryEntry An event that happened on the printer.
// swagger:model EventHistoryEntry
type EventHistoryEntry struct {

	// message
	Message string `json:"message,omitempty"`

	// parameters
	Parameters []string `json:"parameters"`

	// time
	Time strfmt.DateTime `json:"time,omitempty"`

	// type id
	TypeID float64 `json:"type_id,omitempty"`
}

// Validate validates this event history entry
func (m *EventHistoryEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParameters(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventHistoryEntry) validateParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.Parameters) { // not required
		return nil
	}

	return nil
}
