package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Feeder The feeder unit
// swagger:model Feeder
type Feeder struct {

	// Acceleration of the feeder (in mm/s^2)
	Acceleration float64 `json:"acceleration,omitempty"`

	// Acceleration of the acceleration (in mm/s^3)
	Jerk float64 `json:"jerk,omitempty"`

	// Max speed of the feeder in mm/s
	MaxSpeed float64 `json:"max_speed,omitempty"`

	// The position of the feeder. This is otherwise known as the E value
	Position float64 `json:"position,omitempty"`
}

// Validate validates this feeder
func (m *Feeder) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
