package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Led A single (or set) of light source(s)
// swagger:model led
type Led struct {

	// hue
	Hue float64 `json:"hue,omitempty"`

	// saturation
	Saturation float64 `json:"saturation,omitempty"`

	// brightness
	Brightness float64 `json:"brightness,omitempty"`
}

// Validate validates this led
func (m *Led) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
