package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Material material
// swagger:model Material
type Material struct {

	// Unique identifier of the material, empty string if no material loaded.
	GUID string `json:"GUID,omitempty"`

	// mm of filament remaining on spool. Returns -1 if the remaining length is unknown.
	LengthRemaining float64 `json:"length_remaining,omitempty"`
}

// Validate validates this material
func (m *Material) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
