package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// Network network
// swagger:model Network
type Network string

const (
	// NetworkWifi captures enum value "wifi"
	NetworkWifi Network = "wifi"
	// NetworkEthernet captures enum value "ethernet"
	NetworkEthernet Network = "ethernet"
)

// for schema
var networkEnum []interface{}

func init() {
	var res []Network
	if err := json.Unmarshal([]byte(`["wifi","ethernet"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		networkEnum = append(networkEnum, v)
	}
}

func (m Network) validateNetworkEnum(path, location string, value Network) error {
	if err := validate.Enum(path, location, value, networkEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this network
func (m Network) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateNetworkEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
