package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// UUID UUID in UUID4 format.
// swagger:model uuid
type UUID string

// Validate validates this uuid
func (m UUID) Validate(formats strfmt.Registry) error {
	return nil
}
