package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// WifiNetwork wifi network
// swagger:model Wifi_network
type WifiNetwork struct {

	// security required
	SecurityRequired bool `json:"security_required,omitempty"`

	// ssid
	Ssid string `json:"ssid,omitempty"`

	// strength
	Strength int64 `json:"strength,omitempty"`
}

// Validate validates this wifi network
func (m *WifiNetwork) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
