package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/client/authentication"
	"github.com/kabuku/camera-to-led/ultimaker/api/client/camera"
	"github.com/kabuku/camera-to-led/ultimaker/api/client/history"
	"github.com/kabuku/camera-to-led/ultimaker/api/client/materials"
	"github.com/kabuku/camera-to-led/ultimaker/api/client/network"
	"github.com/kabuku/camera-to-led/ultimaker/api/client/print_job"
	"github.com/kabuku/camera-to-led/ultimaker/api/client/printer"
	"github.com/kabuku/camera-to-led/ultimaker/api/client/system"
)

// Default ultimaker HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new ultimaker HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Ultimaker {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new ultimaker HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Ultimaker {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new ultimaker client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Ultimaker {
	cli := new(Ultimaker)
	cli.Transport = transport

	cli.Authentication = authentication.New(transport, formats)

	cli.Camera = camera.New(transport, formats)

	cli.History = history.New(transport, formats)

	cli.Materials = materials.New(transport, formats)

	cli.Network = network.New(transport, formats)

	cli.PrintJob = print_job.New(transport, formats)

	cli.Printer = printer.New(transport, formats)

	cli.System = system.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Ultimaker is a client for ultimaker
type Ultimaker struct {
	Authentication *authentication.Client

	Camera *camera.Client

	History *history.Client

	Materials *materials.Client

	Network *network.Client

	PrintJob *print_job.Client

	Printer *printer.Client

	System *system.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Ultimaker) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Authentication.SetTransport(transport)

	c.Camera.SetTransport(transport)

	c.History.SetTransport(transport)

	c.Materials.SetTransport(transport)

	c.Network.SetTransport(transport)

	c.PrintJob.SetTransport(transport)

	c.Printer.SetTransport(transport)

	c.System.SetTransport(transport)

}
