package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDReader is a Reader for the GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUID structure.
type GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK creates a GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK with default headers values
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK() *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK {
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK{}
}

/*GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK handles this case with default header values.

The GUID of the current active material.
*/
type GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK struct {
	Payload string
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK) Error() string {
	return fmt.Sprintf("[GET /printer/heads/{head_id}/extruders/{extruder_id}/active_material/guid][%d] getPrinterHeadsHeadIdExtrudersExtruderIdActiveMaterialGuidOK  %+v", 200, o.Payload)
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialGUIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
