package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterHeadsHeadIDExtrudersExtruderIDReader is a Reader for the GetPrinterHeadsHeadIDExtrudersExtruderID structure.
type GetPrinterHeadsHeadIDExtrudersExtruderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterHeadsHeadIDExtrudersExtruderIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDOK creates a GetPrinterHeadsHeadIDExtrudersExtruderIDOK with default headers values
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDOK() *GetPrinterHeadsHeadIDExtrudersExtruderIDOK {
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDOK{}
}

/*GetPrinterHeadsHeadIDExtrudersExtruderIDOK handles this case with default header values.

GetPrinterHeadsHeadIDExtrudersExtruderIDOK get printer heads head Id extruders extruder Id o k
*/
type GetPrinterHeadsHeadIDExtrudersExtruderIDOK struct {
	Payload *models.Extruder
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDOK) Error() string {
	return fmt.Sprintf("[GET /printer/heads/{head_id}/extruders/{extruder_id}][%d] getPrinterHeadsHeadIdExtrudersExtruderIdOK  %+v", 200, o.Payload)
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Extruder)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
