package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterLedReader is a Reader for the GetPrinterLed structure.
type GetPrinterLedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterLedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterLedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterLedOK creates a GetPrinterLedOK with default headers values
func NewGetPrinterLedOK() *GetPrinterLedOK {
	return &GetPrinterLedOK{}
}

/*GetPrinterLedOK handles this case with default header values.

HSV the case lighting
*/
type GetPrinterLedOK struct {
	Payload *models.Led
}

func (o *GetPrinterLedOK) Error() string {
	return fmt.Sprintf("[GET /printer/led][%d] getPrinterLedOK  %+v", 200, o.Payload)
}

func (o *GetPrinterLedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Led)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
