package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPrinterStatusReader is a Reader for the GetPrinterStatus structure.
type GetPrinterStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterStatusOK creates a GetPrinterStatusOK with default headers values
func NewGetPrinterStatusOK() *GetPrinterStatusOK {
	return &GetPrinterStatusOK{}
}

/*GetPrinterStatusOK handles this case with default header values.

Global status of the printer, most interesting ones are 'idle' which means the printer can accept a print job. And 'printing' which means the printer is actively working on a print job.
*/
type GetPrinterStatusOK struct {
	Payload string
}

func (o *GetPrinterStatusOK) Error() string {
	return fmt.Sprintf("[GET /printer/status][%d] getPrinterStatusOK  %+v", 200, o.Payload)
}

func (o *GetPrinterStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
