package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterHeadsReader is a Reader for the GetPrinterHeads structure.
type GetPrinterHeadsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterHeadsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterHeadsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterHeadsOK creates a GetPrinterHeadsOK with default headers values
func NewGetPrinterHeadsOK() *GetPrinterHeadsOK {
	return &GetPrinterHeadsOK{}
}

/*GetPrinterHeadsOK handles this case with default header values.

GetPrinterHeadsOK get printer heads o k
*/
type GetPrinterHeadsOK struct {
	Payload []*models.Head
}

func (o *GetPrinterHeadsOK) Error() string {
	return fmt.Sprintf("[GET /printer/heads][%d] getPrinterHeadsOK  %+v", 200, o.Payload)
}

func (o *GetPrinterHeadsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
