package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterHeadsHeadIDJerkReader is a Reader for the GetPrinterHeadsHeadIDJerk structure.
type GetPrinterHeadsHeadIDJerkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterHeadsHeadIDJerkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterHeadsHeadIDJerkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterHeadsHeadIDJerkOK creates a GetPrinterHeadsHeadIDJerkOK with default headers values
func NewGetPrinterHeadsHeadIDJerkOK() *GetPrinterHeadsHeadIDJerkOK {
	return &GetPrinterHeadsHeadIDJerkOK{}
}

/*GetPrinterHeadsHeadIDJerkOK handles this case with default header values.

GetPrinterHeadsHeadIDJerkOK get printer heads head Id jerk o k
*/
type GetPrinterHeadsHeadIDJerkOK struct {
	Payload *models.XYZ
}

func (o *GetPrinterHeadsHeadIDJerkOK) Error() string {
	return fmt.Sprintf("[GET /printer/heads/{head_id}/jerk][%d] getPrinterHeadsHeadIdJerkOK  %+v", 200, o.Payload)
}

func (o *GetPrinterHeadsHeadIDJerkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.XYZ)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
