package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams creates a new GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams object
// with the default values initialized.
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams() *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	var ()
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParamsWithTimeout creates a new GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParamsWithTimeout(timeout time.Duration) *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	var ()
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams{

		timeout: timeout,
	}
}

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParamsWithContext creates a new GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParamsWithContext(ctx context.Context) *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	var ()
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams{

		Context: ctx,
	}
}

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParamsWithHTTPClient creates a new GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParamsWithHTTPClient(client *http.Client) *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	var ()
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams{
		HTTPClient: client,
	}
}

/*GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams contains all the parameters to send to the API endpoint
for the get printer heads head ID extruders extruder ID active material length remaining operation typically these are written to a http.Request
*/
type GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams struct {

	/*ExtruderID
	  ID of extruder from which the hotend is fetched

	*/
	ExtruderID int64
	/*HeadID
	  ID of head from which the hotend is fetched

	*/
	HeadID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) WithTimeout(timeout time.Duration) *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) WithContext(ctx context.Context) *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) WithHTTPClient(client *http.Client) *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExtruderID adds the extruderID to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) WithExtruderID(extruderID int64) *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	o.SetExtruderID(extruderID)
	return o
}

// SetExtruderID adds the extruderId to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) SetExtruderID(extruderID int64) {
	o.ExtruderID = extruderID
}

// WithHeadID adds the headID to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) WithHeadID(headID int64) *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams {
	o.SetHeadID(headID)
	return o
}

// SetHeadID adds the headId to the get printer heads head ID extruders extruder ID active material length remaining params
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) SetHeadID(headID int64) {
	o.HeadID = headID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDActiveMaterialLengthRemainingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param extruder_id
	if err := r.SetPathParam("extruder_id", swag.FormatInt64(o.ExtruderID)); err != nil {
		return err
	}

	// path param head_id
	if err := r.SetPathParam("head_id", swag.FormatInt64(o.HeadID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
