package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrinterHeadsHeadIDJerkParams creates a new GetPrinterHeadsHeadIDJerkParams object
// with the default values initialized.
func NewGetPrinterHeadsHeadIDJerkParams() *GetPrinterHeadsHeadIDJerkParams {
	var ()
	return &GetPrinterHeadsHeadIDJerkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrinterHeadsHeadIDJerkParamsWithTimeout creates a new GetPrinterHeadsHeadIDJerkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrinterHeadsHeadIDJerkParamsWithTimeout(timeout time.Duration) *GetPrinterHeadsHeadIDJerkParams {
	var ()
	return &GetPrinterHeadsHeadIDJerkParams{

		timeout: timeout,
	}
}

// NewGetPrinterHeadsHeadIDJerkParamsWithContext creates a new GetPrinterHeadsHeadIDJerkParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrinterHeadsHeadIDJerkParamsWithContext(ctx context.Context) *GetPrinterHeadsHeadIDJerkParams {
	var ()
	return &GetPrinterHeadsHeadIDJerkParams{

		Context: ctx,
	}
}

// NewGetPrinterHeadsHeadIDJerkParamsWithHTTPClient creates a new GetPrinterHeadsHeadIDJerkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrinterHeadsHeadIDJerkParamsWithHTTPClient(client *http.Client) *GetPrinterHeadsHeadIDJerkParams {
	var ()
	return &GetPrinterHeadsHeadIDJerkParams{
		HTTPClient: client,
	}
}

/*GetPrinterHeadsHeadIDJerkParams contains all the parameters to send to the API endpoint
for the get printer heads head ID jerk operation typically these are written to a http.Request
*/
type GetPrinterHeadsHeadIDJerkParams struct {

	/*HeadID
	  ID of head of which to get the jerk of. Note that this speed also has a Z component. This API assumes that the head is the only part that moves.

	*/
	HeadID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get printer heads head ID jerk params
func (o *GetPrinterHeadsHeadIDJerkParams) WithTimeout(timeout time.Duration) *GetPrinterHeadsHeadIDJerkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get printer heads head ID jerk params
func (o *GetPrinterHeadsHeadIDJerkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get printer heads head ID jerk params
func (o *GetPrinterHeadsHeadIDJerkParams) WithContext(ctx context.Context) *GetPrinterHeadsHeadIDJerkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get printer heads head ID jerk params
func (o *GetPrinterHeadsHeadIDJerkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get printer heads head ID jerk params
func (o *GetPrinterHeadsHeadIDJerkParams) WithHTTPClient(client *http.Client) *GetPrinterHeadsHeadIDJerkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get printer heads head ID jerk params
func (o *GetPrinterHeadsHeadIDJerkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeadID adds the headID to the get printer heads head ID jerk params
func (o *GetPrinterHeadsHeadIDJerkParams) WithHeadID(headID int64) *GetPrinterHeadsHeadIDJerkParams {
	o.SetHeadID(headID)
	return o
}

// SetHeadID adds the headId to the get printer heads head ID jerk params
func (o *GetPrinterHeadsHeadIDJerkParams) SetHeadID(headID int64) {
	o.HeadID = headID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrinterHeadsHeadIDJerkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param head_id
	if err := r.SetPathParam("head_id", swag.FormatInt64(o.HeadID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
