package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkReader is a Reader for the GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerk structure.
type GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK creates a GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK with default headers values
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK() *GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK {
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK{}
}

/*GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK handles this case with default header values.

GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK get printer heads head Id extruders extruder Id feeder jerk o k
*/
type GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK struct {
	Payload float64
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK) Error() string {
	return fmt.Sprintf("[GET /printer/heads/{head_id}/extruders/{extruder_id}/feeder/jerk][%d] getPrinterHeadsHeadIdExtrudersExtruderIdFeederJerkOK  %+v", 200, o.Payload)
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
