package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterHeadsHeadIDExtrudersExtruderIDFeederReader is a Reader for the GetPrinterHeadsHeadIDExtrudersExtruderIDFeeder structure.
type GetPrinterHeadsHeadIDExtrudersExtruderIDFeederReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDFeederReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK creates a GetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK with default headers values
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK() *GetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK {
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK{}
}

/*GetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK handles this case with default header values.

GetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK get printer heads head Id extruders extruder Id feeder o k
*/
type GetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK struct {
	Payload *models.Feeder
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK) Error() string {
	return fmt.Sprintf("[GET /printer/heads/{head_id}/extruders/{extruder_id}/feeder][%d] getPrinterHeadsHeadIdExtrudersExtruderIdFeederOK  %+v", 200, o.Payload)
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDFeederOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Feeder)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
