package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterHeadsHeadIDExtrudersReader is a Reader for the GetPrinterHeadsHeadIDExtruders structure.
type GetPrinterHeadsHeadIDExtrudersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterHeadsHeadIDExtrudersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterHeadsHeadIDExtrudersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterHeadsHeadIDExtrudersOK creates a GetPrinterHeadsHeadIDExtrudersOK with default headers values
func NewGetPrinterHeadsHeadIDExtrudersOK() *GetPrinterHeadsHeadIDExtrudersOK {
	return &GetPrinterHeadsHeadIDExtrudersOK{}
}

/*GetPrinterHeadsHeadIDExtrudersOK handles this case with default header values.

GetPrinterHeadsHeadIDExtrudersOK get printer heads head Id extruders o k
*/
type GetPrinterHeadsHeadIDExtrudersOK struct {
	Payload []*models.Extruder
}

func (o *GetPrinterHeadsHeadIDExtrudersOK) Error() string {
	return fmt.Sprintf("[GET /printer/heads/{head_id}/extruders/][%d] getPrinterHeadsHeadIdExtrudersOK  %+v", 200, o.Payload)
}

func (o *GetPrinterHeadsHeadIDExtrudersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
