package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrinterHeadsHeadIDParams creates a new GetPrinterHeadsHeadIDParams object
// with the default values initialized.
func NewGetPrinterHeadsHeadIDParams() *GetPrinterHeadsHeadIDParams {
	var ()
	return &GetPrinterHeadsHeadIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrinterHeadsHeadIDParamsWithTimeout creates a new GetPrinterHeadsHeadIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrinterHeadsHeadIDParamsWithTimeout(timeout time.Duration) *GetPrinterHeadsHeadIDParams {
	var ()
	return &GetPrinterHeadsHeadIDParams{

		timeout: timeout,
	}
}

// NewGetPrinterHeadsHeadIDParamsWithContext creates a new GetPrinterHeadsHeadIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrinterHeadsHeadIDParamsWithContext(ctx context.Context) *GetPrinterHeadsHeadIDParams {
	var ()
	return &GetPrinterHeadsHeadIDParams{

		Context: ctx,
	}
}

// NewGetPrinterHeadsHeadIDParamsWithHTTPClient creates a new GetPrinterHeadsHeadIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrinterHeadsHeadIDParamsWithHTTPClient(client *http.Client) *GetPrinterHeadsHeadIDParams {
	var ()
	return &GetPrinterHeadsHeadIDParams{
		HTTPClient: client,
	}
}

/*GetPrinterHeadsHeadIDParams contains all the parameters to send to the API endpoint
for the get printer heads head ID operation typically these are written to a http.Request
*/
type GetPrinterHeadsHeadIDParams struct {

	/*HeadID
	  ID of head to fetch

	*/
	HeadID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get printer heads head ID params
func (o *GetPrinterHeadsHeadIDParams) WithTimeout(timeout time.Duration) *GetPrinterHeadsHeadIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get printer heads head ID params
func (o *GetPrinterHeadsHeadIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get printer heads head ID params
func (o *GetPrinterHeadsHeadIDParams) WithContext(ctx context.Context) *GetPrinterHeadsHeadIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get printer heads head ID params
func (o *GetPrinterHeadsHeadIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get printer heads head ID params
func (o *GetPrinterHeadsHeadIDParams) WithHTTPClient(client *http.Client) *GetPrinterHeadsHeadIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get printer heads head ID params
func (o *GetPrinterHeadsHeadIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeadID adds the headID to the get printer heads head ID params
func (o *GetPrinterHeadsHeadIDParams) WithHeadID(headID int64) *GetPrinterHeadsHeadIDParams {
	o.SetHeadID(headID)
	return o
}

// SetHeadID adds the headId to the get printer heads head ID params
func (o *GetPrinterHeadsHeadIDParams) SetHeadID(headID int64) {
	o.HeadID = headID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrinterHeadsHeadIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param head_id
	if err := r.SetPathParam("head_id", swag.FormatInt64(o.HeadID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
