package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureReader is a Reader for the GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperature structure.
type GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK creates a GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK with default headers values
func NewGetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK() *GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK {
	return &GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK{}
}

/*GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK handles this case with default header values.

Temperature of the hotend
*/
type GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK struct {
	Payload *models.CurrentTargetNumberPair
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK) Error() string {
	return fmt.Sprintf("[GET /printer/heads/{head_id}/extruders/{extruder_id}/hotend/temperature][%d] getPrinterHeadsHeadIdExtrudersExtruderIdHotendTemperatureOK  %+v", 200, o.Payload)
}

func (o *GetPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CurrentTargetNumberPair)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
