package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterBedReader is a Reader for the GetPrinterBed structure.
type GetPrinterBedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterBedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterBedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterBedOK creates a GetPrinterBedOK with default headers values
func NewGetPrinterBedOK() *GetPrinterBedOK {
	return &GetPrinterBedOK{}
}

/*GetPrinterBedOK handles this case with default header values.

bed object
*/
type GetPrinterBedOK struct {
	Payload *models.Bed
}

func (o *GetPrinterBedOK) Error() string {
	return fmt.Sprintf("[GET /printer/bed][%d] getPrinterBedOK  %+v", 200, o.Payload)
}

func (o *GetPrinterBedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Bed)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
