package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPrinterDiagnosticsCapSensorNoiseReader is a Reader for the GetPrinterDiagnosticsCapSensorNoise structure.
type GetPrinterDiagnosticsCapSensorNoiseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterDiagnosticsCapSensorNoiseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterDiagnosticsCapSensorNoiseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetPrinterDiagnosticsCapSensorNoiseBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterDiagnosticsCapSensorNoiseOK creates a GetPrinterDiagnosticsCapSensorNoiseOK with default headers values
func NewGetPrinterDiagnosticsCapSensorNoiseOK() *GetPrinterDiagnosticsCapSensorNoiseOK {
	return &GetPrinterDiagnosticsCapSensorNoiseOK{}
}

/*GetPrinterDiagnosticsCapSensorNoiseOK handles this case with default header values.

A list of dictionairies containing the min, max, avg and stddev^2 values
*/
type GetPrinterDiagnosticsCapSensorNoiseOK struct {
}

func (o *GetPrinterDiagnosticsCapSensorNoiseOK) Error() string {
	return fmt.Sprintf("[GET /printer/diagnostics/cap_sensor_noise][%d] getPrinterDiagnosticsCapSensorNoiseOK ", 200)
}

func (o *GetPrinterDiagnosticsCapSensorNoiseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPrinterDiagnosticsCapSensorNoiseBadRequest creates a GetPrinterDiagnosticsCapSensorNoiseBadRequest with default headers values
func NewGetPrinterDiagnosticsCapSensorNoiseBadRequest() *GetPrinterDiagnosticsCapSensorNoiseBadRequest {
	return &GetPrinterDiagnosticsCapSensorNoiseBadRequest{}
}

/*GetPrinterDiagnosticsCapSensorNoiseBadRequest handles this case with default header values.

When a timeout occurs (taking too long to get the data) or when the printer is already busy
*/
type GetPrinterDiagnosticsCapSensorNoiseBadRequest struct {
}

func (o *GetPrinterDiagnosticsCapSensorNoiseBadRequest) Error() string {
	return fmt.Sprintf("[GET /printer/diagnostics/cap_sensor_noise][%d] getPrinterDiagnosticsCapSensorNoiseBadRequest ", 400)
}

func (o *GetPrinterDiagnosticsCapSensorNoiseBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
