package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutPrinterHeadsHeadIDAccelerationReader is a Reader for the PutPrinterHeadsHeadIDAcceleration structure.
type PutPrinterHeadsHeadIDAccelerationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPrinterHeadsHeadIDAccelerationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutPrinterHeadsHeadIDAccelerationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutPrinterHeadsHeadIDAccelerationNoContent creates a PutPrinterHeadsHeadIDAccelerationNoContent with default headers values
func NewPutPrinterHeadsHeadIDAccelerationNoContent() *PutPrinterHeadsHeadIDAccelerationNoContent {
	return &PutPrinterHeadsHeadIDAccelerationNoContent{}
}

/*PutPrinterHeadsHeadIDAccelerationNoContent handles this case with default header values.

acceleration speed set
*/
type PutPrinterHeadsHeadIDAccelerationNoContent struct {
}

func (o *PutPrinterHeadsHeadIDAccelerationNoContent) Error() string {
	return fmt.Sprintf("[PUT /printer/heads/{head_id}/acceleration][%d] putPrinterHeadsHeadIdAccelerationNoContent ", 204)
}

func (o *PutPrinterHeadsHeadIDAccelerationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
