package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedReader is a Reader for the PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeed structure.
type PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent creates a PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent with default headers values
func NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent() *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent {
	return &PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent{}
}

/*PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent handles this case with default header values.

Max speed set
*/
type PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent struct {
}

func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent) Error() string {
	return fmt.Sprintf("[PUT /printer/heads/{head_id}/extruders/{extruder_id}/feeder/max_speed][%d] putPrinterHeadsHeadIdExtrudersExtruderIdFeederMaxSpeedNoContent ", 204)
}

func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
