package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutPrinterHeadsHeadIDPositionReader is a Reader for the PutPrinterHeadsHeadIDPosition structure.
type PutPrinterHeadsHeadIDPositionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPrinterHeadsHeadIDPositionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutPrinterHeadsHeadIDPositionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutPrinterHeadsHeadIDPositionNoContent creates a PutPrinterHeadsHeadIDPositionNoContent with default headers values
func NewPutPrinterHeadsHeadIDPositionNoContent() *PutPrinterHeadsHeadIDPositionNoContent {
	return &PutPrinterHeadsHeadIDPositionNoContent{}
}

/*PutPrinterHeadsHeadIDPositionNoContent handles this case with default header values.

Position set
*/
type PutPrinterHeadsHeadIDPositionNoContent struct {
}

func (o *PutPrinterHeadsHeadIDPositionNoContent) Error() string {
	return fmt.Sprintf("[PUT /printer/heads/{head_id}/position][%d] putPrinterHeadsHeadIdPositionNoContent ", 204)
}

func (o *PutPrinterHeadsHeadIDPositionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
