package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams creates a new PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams object
// with the default values initialized.
func NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams() *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	var ()
	return &PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParamsWithTimeout creates a new PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParamsWithTimeout(timeout time.Duration) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	var ()
	return &PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams{

		timeout: timeout,
	}
}

// NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParamsWithContext creates a new PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParamsWithContext(ctx context.Context) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	var ()
	return &PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams{

		Context: ctx,
	}
}

// NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParamsWithHTTPClient creates a new PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParamsWithHTTPClient(client *http.Client) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	var ()
	return &PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams{
		HTTPClient: client,
	}
}

/*PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams contains all the parameters to send to the API endpoint
for the put printer heads head ID extruders extruder ID feeder max speed operation typically these are written to a http.Request
*/
type PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams struct {

	/*ExtruderID
	  ID of extruder from which the feeder is fetched

	*/
	ExtruderID int64
	/*HeadID
	  ID of head from which the extruder is fetched

	*/
	HeadID int64
	/*MaxSpeed
	  Target max speed

	*/
	MaxSpeed *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) WithTimeout(timeout time.Duration) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) WithContext(ctx context.Context) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) WithHTTPClient(client *http.Client) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExtruderID adds the extruderID to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) WithExtruderID(extruderID int64) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	o.SetExtruderID(extruderID)
	return o
}

// SetExtruderID adds the extruderId to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) SetExtruderID(extruderID int64) {
	o.ExtruderID = extruderID
}

// WithHeadID adds the headID to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) WithHeadID(headID int64) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	o.SetHeadID(headID)
	return o
}

// SetHeadID adds the headId to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) SetHeadID(headID int64) {
	o.HeadID = headID
}

// WithMaxSpeed adds the maxSpeed to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) WithMaxSpeed(maxSpeed *float64) *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams {
	o.SetMaxSpeed(maxSpeed)
	return o
}

// SetMaxSpeed adds the maxSpeed to the put printer heads head ID extruders extruder ID feeder max speed params
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) SetMaxSpeed(maxSpeed *float64) {
	o.MaxSpeed = maxSpeed
}

// WriteToRequest writes these params to a swagger request
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederMaxSpeedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param extruder_id
	if err := r.SetPathParam("extruder_id", swag.FormatInt64(o.ExtruderID)); err != nil {
		return err
	}

	// path param head_id
	if err := r.SetPathParam("head_id", swag.FormatInt64(o.HeadID)); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.MaxSpeed); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
