package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkReader is a Reader for the PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerk structure.
type PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent creates a PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent with default headers values
func NewPutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent() *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent {
	return &PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent{}
}

/*PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent handles this case with default header values.

Jerk set
*/
type PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent struct {
}

func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent) Error() string {
	return fmt.Sprintf("[PUT /printer/heads/{head_id}/extruders/{extruder_id}/feeder/jerk][%d] putPrinterHeadsHeadIdExtrudersExtruderIdFeederJerkNoContent ", 204)
}

func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDFeederJerkNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
