package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutPrinterHeadsHeadIDAccelerationParams creates a new PutPrinterHeadsHeadIDAccelerationParams object
// with the default values initialized.
func NewPutPrinterHeadsHeadIDAccelerationParams() *PutPrinterHeadsHeadIDAccelerationParams {
	var ()
	return &PutPrinterHeadsHeadIDAccelerationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutPrinterHeadsHeadIDAccelerationParamsWithTimeout creates a new PutPrinterHeadsHeadIDAccelerationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutPrinterHeadsHeadIDAccelerationParamsWithTimeout(timeout time.Duration) *PutPrinterHeadsHeadIDAccelerationParams {
	var ()
	return &PutPrinterHeadsHeadIDAccelerationParams{

		timeout: timeout,
	}
}

// NewPutPrinterHeadsHeadIDAccelerationParamsWithContext creates a new PutPrinterHeadsHeadIDAccelerationParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutPrinterHeadsHeadIDAccelerationParamsWithContext(ctx context.Context) *PutPrinterHeadsHeadIDAccelerationParams {
	var ()
	return &PutPrinterHeadsHeadIDAccelerationParams{

		Context: ctx,
	}
}

// NewPutPrinterHeadsHeadIDAccelerationParamsWithHTTPClient creates a new PutPrinterHeadsHeadIDAccelerationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutPrinterHeadsHeadIDAccelerationParamsWithHTTPClient(client *http.Client) *PutPrinterHeadsHeadIDAccelerationParams {
	var ()
	return &PutPrinterHeadsHeadIDAccelerationParams{
		HTTPClient: client,
	}
}

/*PutPrinterHeadsHeadIDAccelerationParams contains all the parameters to send to the API endpoint
for the put printer heads head ID acceleration operation typically these are written to a http.Request
*/
type PutPrinterHeadsHeadIDAccelerationParams struct {

	/*Acceleration
	  Target default acceleration.

	*/
	Acceleration *float64
	/*HeadID*/
	HeadID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) WithTimeout(timeout time.Duration) *PutPrinterHeadsHeadIDAccelerationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) WithContext(ctx context.Context) *PutPrinterHeadsHeadIDAccelerationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) WithHTTPClient(client *http.Client) *PutPrinterHeadsHeadIDAccelerationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAcceleration adds the acceleration to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) WithAcceleration(acceleration *float64) *PutPrinterHeadsHeadIDAccelerationParams {
	o.SetAcceleration(acceleration)
	return o
}

// SetAcceleration adds the acceleration to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) SetAcceleration(acceleration *float64) {
	o.Acceleration = acceleration
}

// WithHeadID adds the headID to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) WithHeadID(headID int64) *PutPrinterHeadsHeadIDAccelerationParams {
	o.SetHeadID(headID)
	return o
}

// SetHeadID adds the headId to the put printer heads head ID acceleration params
func (o *PutPrinterHeadsHeadIDAccelerationParams) SetHeadID(headID int64) {
	o.HeadID = headID
}

// WriteToRequest writes these params to a swagger request
func (o *PutPrinterHeadsHeadIDAccelerationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Acceleration); err != nil {
		return err
	}

	// path param head_id
	if err := r.SetPathParam("head_id", swag.FormatInt64(o.HeadID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
