package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutPrinterBedTemperatureReader is a Reader for the PutPrinterBedTemperature structure.
type PutPrinterBedTemperatureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPrinterBedTemperatureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutPrinterBedTemperatureNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutPrinterBedTemperatureNoContent creates a PutPrinterBedTemperatureNoContent with default headers values
func NewPutPrinterBedTemperatureNoContent() *PutPrinterBedTemperatureNoContent {
	return &PutPrinterBedTemperatureNoContent{}
}

/*PutPrinterBedTemperatureNoContent handles this case with default header values.

Temperature set
*/
type PutPrinterBedTemperatureNoContent struct {
}

func (o *PutPrinterBedTemperatureNoContent) Error() string {
	return fmt.Sprintf("[PUT /printer/bed/temperature][%d] putPrinterBedTemperatureNoContent ", 204)
}

func (o *PutPrinterBedTemperatureNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
