package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureReader is a Reader for the PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperature structure.
type PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent creates a PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent with default headers values
func NewPutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent() *PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent {
	return &PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent{}
}

/*PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent handles this case with default header values.

Temperature set
*/
type PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent struct {
}

func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent) Error() string {
	return fmt.Sprintf("[PUT /printer/heads/{head_id}/extruders/{extruder_id}/hotend/temperature][%d] putPrinterHeadsHeadIdExtrudersExtruderIdHotendTemperatureNoContent ", 204)
}

func (o *PutPrinterHeadsHeadIDExtrudersExtruderIDHotendTemperatureNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
