package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// NewPutPrinterHeadsHeadIDPositionParams creates a new PutPrinterHeadsHeadIDPositionParams object
// with the default values initialized.
func NewPutPrinterHeadsHeadIDPositionParams() *PutPrinterHeadsHeadIDPositionParams {
	var ()
	return &PutPrinterHeadsHeadIDPositionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutPrinterHeadsHeadIDPositionParamsWithTimeout creates a new PutPrinterHeadsHeadIDPositionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutPrinterHeadsHeadIDPositionParamsWithTimeout(timeout time.Duration) *PutPrinterHeadsHeadIDPositionParams {
	var ()
	return &PutPrinterHeadsHeadIDPositionParams{

		timeout: timeout,
	}
}

// NewPutPrinterHeadsHeadIDPositionParamsWithContext creates a new PutPrinterHeadsHeadIDPositionParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutPrinterHeadsHeadIDPositionParamsWithContext(ctx context.Context) *PutPrinterHeadsHeadIDPositionParams {
	var ()
	return &PutPrinterHeadsHeadIDPositionParams{

		Context: ctx,
	}
}

// NewPutPrinterHeadsHeadIDPositionParamsWithHTTPClient creates a new PutPrinterHeadsHeadIDPositionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutPrinterHeadsHeadIDPositionParamsWithHTTPClient(client *http.Client) *PutPrinterHeadsHeadIDPositionParams {
	var ()
	return &PutPrinterHeadsHeadIDPositionParams{
		HTTPClient: client,
	}
}

/*PutPrinterHeadsHeadIDPositionParams contains all the parameters to send to the API endpoint
for the put printer heads head ID position operation typically these are written to a http.Request
*/
type PutPrinterHeadsHeadIDPositionParams struct {

	/*HeadID
	  ID of head from which the hotend is fetched

	*/
	HeadID int64
	/*Position
	  Target position

	*/
	Position *models.XYZ

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) WithTimeout(timeout time.Duration) *PutPrinterHeadsHeadIDPositionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) WithContext(ctx context.Context) *PutPrinterHeadsHeadIDPositionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) WithHTTPClient(client *http.Client) *PutPrinterHeadsHeadIDPositionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeadID adds the headID to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) WithHeadID(headID int64) *PutPrinterHeadsHeadIDPositionParams {
	o.SetHeadID(headID)
	return o
}

// SetHeadID adds the headId to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) SetHeadID(headID int64) {
	o.HeadID = headID
}

// WithPosition adds the position to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) WithPosition(position *models.XYZ) *PutPrinterHeadsHeadIDPositionParams {
	o.SetPosition(position)
	return o
}

// SetPosition adds the position to the put printer heads head ID position params
func (o *PutPrinterHeadsHeadIDPositionParams) SetPosition(position *models.XYZ) {
	o.Position = position
}

// WriteToRequest writes these params to a swagger request
func (o *PutPrinterHeadsHeadIDPositionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param head_id
	if err := r.SetPathParam("head_id", swag.FormatInt64(o.HeadID)); err != nil {
		return err
	}

	if o.Position == nil {
		o.Position = new(models.XYZ)
	}

	if err := r.SetBodyParam(o.Position); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
