package camera

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCameraFeedReader is a Reader for the GetCameraFeed structure.
type GetCameraFeedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCameraFeedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCameraFeedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCameraFeedOK creates a GetCameraFeedOK with default headers values
func NewGetCameraFeedOK() *GetCameraFeedOK {
	return &GetCameraFeedOK{}
}

/*GetCameraFeedOK handles this case with default header values.

Camera feed
*/
type GetCameraFeedOK struct {
	Payload string
}

func (o *GetCameraFeedOK) Error() string {
	return fmt.Sprintf("[GET /camera/feed][%d] getCameraFeedOK  %+v", 200, o.Payload)
}

func (o *GetCameraFeedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
