package camera

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCameraParams creates a new GetCameraParams object
// with the default values initialized.
func NewGetCameraParams() *GetCameraParams {

	return &GetCameraParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCameraParamsWithTimeout creates a new GetCameraParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCameraParamsWithTimeout(timeout time.Duration) *GetCameraParams {

	return &GetCameraParams{

		timeout: timeout,
	}
}

// NewGetCameraParamsWithContext creates a new GetCameraParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCameraParamsWithContext(ctx context.Context) *GetCameraParams {

	return &GetCameraParams{

		Context: ctx,
	}
}

// NewGetCameraParamsWithHTTPClient creates a new GetCameraParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCameraParamsWithHTTPClient(client *http.Client) *GetCameraParams {

	return &GetCameraParams{
		HTTPClient: client,
	}
}

/*GetCameraParams contains all the parameters to send to the API endpoint
for the get camera operation typically these are written to a http.Request
*/
type GetCameraParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get camera params
func (o *GetCameraParams) WithTimeout(timeout time.Duration) *GetCameraParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get camera params
func (o *GetCameraParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get camera params
func (o *GetCameraParams) WithContext(ctx context.Context) *GetCameraParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get camera params
func (o *GetCameraParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get camera params
func (o *GetCameraParams) WithHTTPClient(client *http.Client) *GetCameraParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get camera params
func (o *GetCameraParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCameraParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
