package camera

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCameraFeedParams creates a new GetCameraFeedParams object
// with the default values initialized.
func NewGetCameraFeedParams() *GetCameraFeedParams {

	return &GetCameraFeedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCameraFeedParamsWithTimeout creates a new GetCameraFeedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCameraFeedParamsWithTimeout(timeout time.Duration) *GetCameraFeedParams {

	return &GetCameraFeedParams{

		timeout: timeout,
	}
}

// NewGetCameraFeedParamsWithContext creates a new GetCameraFeedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCameraFeedParamsWithContext(ctx context.Context) *GetCameraFeedParams {

	return &GetCameraFeedParams{

		Context: ctx,
	}
}

// NewGetCameraFeedParamsWithHTTPClient creates a new GetCameraFeedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCameraFeedParamsWithHTTPClient(client *http.Client) *GetCameraFeedParams {

	return &GetCameraFeedParams{
		HTTPClient: client,
	}
}

/*GetCameraFeedParams contains all the parameters to send to the API endpoint
for the get camera feed operation typically these are written to a http.Request
*/
type GetCameraFeedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get camera feed params
func (o *GetCameraFeedParams) WithTimeout(timeout time.Duration) *GetCameraFeedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get camera feed params
func (o *GetCameraFeedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get camera feed params
func (o *GetCameraFeedParams) WithContext(ctx context.Context) *GetCameraFeedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get camera feed params
func (o *GetCameraFeedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get camera feed params
func (o *GetCameraFeedParams) WithHTTPClient(client *http.Client) *GetCameraFeedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get camera feed params
func (o *GetCameraFeedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCameraFeedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
