package materials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"os"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostMaterialsParams creates a new PostMaterialsParams object
// with the default values initialized.
func NewPostMaterialsParams() *PostMaterialsParams {
	var ()
	return &PostMaterialsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMaterialsParamsWithTimeout creates a new PostMaterialsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMaterialsParamsWithTimeout(timeout time.Duration) *PostMaterialsParams {
	var ()
	return &PostMaterialsParams{

		timeout: timeout,
	}
}

// NewPostMaterialsParamsWithContext creates a new PostMaterialsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMaterialsParamsWithContext(ctx context.Context) *PostMaterialsParams {
	var ()
	return &PostMaterialsParams{

		Context: ctx,
	}
}

// NewPostMaterialsParamsWithHTTPClient creates a new PostMaterialsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMaterialsParamsWithHTTPClient(client *http.Client) *PostMaterialsParams {
	var ()
	return &PostMaterialsParams{
		HTTPClient: client,
	}
}

/*PostMaterialsParams contains all the parameters to send to the API endpoint
for the post materials operation typically these are written to a http.Request
*/
type PostMaterialsParams struct {

	/*File
	  Material file (.xml)

	*/
	File os.File
	/*Filename
	  Name of the file

	*/
	Filename string
	/*SignatureFile
	  Signature file (.sig)

	*/
	SignatureFile *os.File

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post materials params
func (o *PostMaterialsParams) WithTimeout(timeout time.Duration) *PostMaterialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post materials params
func (o *PostMaterialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post materials params
func (o *PostMaterialsParams) WithContext(ctx context.Context) *PostMaterialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post materials params
func (o *PostMaterialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post materials params
func (o *PostMaterialsParams) WithHTTPClient(client *http.Client) *PostMaterialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post materials params
func (o *PostMaterialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the post materials params
func (o *PostMaterialsParams) WithFile(file os.File) *PostMaterialsParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the post materials params
func (o *PostMaterialsParams) SetFile(file os.File) {
	o.File = file
}

// WithFilename adds the filename to the post materials params
func (o *PostMaterialsParams) WithFilename(filename string) *PostMaterialsParams {
	o.SetFilename(filename)
	return o
}

// SetFilename adds the filename to the post materials params
func (o *PostMaterialsParams) SetFilename(filename string) {
	o.Filename = filename
}

// WithSignatureFile adds the signatureFile to the post materials params
func (o *PostMaterialsParams) WithSignatureFile(signatureFile *os.File) *PostMaterialsParams {
	o.SetSignatureFile(signatureFile)
	return o
}

// SetSignatureFile adds the signatureFile to the post materials params
func (o *PostMaterialsParams) SetSignatureFile(signatureFile *os.File) {
	o.SignatureFile = signatureFile
}

// WriteToRequest writes these params to a swagger request
func (o *PostMaterialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form file param file
	if err := r.SetFileParam("file", &o.File); err != nil {
		return err
	}

	// form param filename
	frFilename := o.Filename
	fFilename := frFilename
	if fFilename != "" {
		if err := r.SetFormParam("filename", fFilename); err != nil {
			return err
		}
	}

	if o.SignatureFile != nil {

		if o.SignatureFile != nil {

			// form file param signature_file
			if err := r.SetFileParam("signature_file", o.SignatureFile); err != nil {
				return err
			}

		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
