package materials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMaterialsReader is a Reader for the PostMaterials structure.
type PostMaterialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMaterialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPostMaterialsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMaterialsNoContent creates a PostMaterialsNoContent with default headers values
func NewPostMaterialsNoContent() *PostMaterialsNoContent {
	return &PostMaterialsNoContent{}
}

/*PostMaterialsNoContent handles this case with default header values.

Material profile added.
*/
type PostMaterialsNoContent struct {
}

func (o *PostMaterialsNoContent) Error() string {
	return fmt.Sprintf("[POST /materials][%d] postMaterialsNoContent ", 204)
}

func (o *PostMaterialsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
