package materials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutMaterialsMaterialGUIDReader is a Reader for the PutMaterialsMaterialGUID structure.
type PutMaterialsMaterialGUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutMaterialsMaterialGUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutMaterialsMaterialGUIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutMaterialsMaterialGUIDNoContent creates a PutMaterialsMaterialGUIDNoContent with default headers values
func NewPutMaterialsMaterialGUIDNoContent() *PutMaterialsMaterialGUIDNoContent {
	return &PutMaterialsMaterialGUIDNoContent{}
}

/*PutMaterialsMaterialGUIDNoContent handles this case with default header values.

Material updated
*/
type PutMaterialsMaterialGUIDNoContent struct {
}

func (o *PutMaterialsMaterialGUIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /materials/{material_guid}/][%d] putMaterialsMaterialGuidNoContent ", 204)
}

func (o *PutMaterialsMaterialGUIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
