package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeletePrinterNetworkWifiNetworksSsidReader is a Reader for the DeletePrinterNetworkWifiNetworksSsid structure.
type DeletePrinterNetworkWifiNetworksSsidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePrinterNetworkWifiNetworksSsidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeletePrinterNetworkWifiNetworksSsidNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePrinterNetworkWifiNetworksSsidNoContent creates a DeletePrinterNetworkWifiNetworksSsidNoContent with default headers values
func NewDeletePrinterNetworkWifiNetworksSsidNoContent() *DeletePrinterNetworkWifiNetworksSsidNoContent {
	return &DeletePrinterNetworkWifiNetworksSsidNoContent{}
}

/*DeletePrinterNetworkWifiNetworksSsidNoContent handles this case with default header values.

DeletePrinterNetworkWifiNetworksSsidNoContent delete printer network wifi networks ssid no content
*/
type DeletePrinterNetworkWifiNetworksSsidNoContent struct {
}

func (o *DeletePrinterNetworkWifiNetworksSsidNoContent) Error() string {
	return fmt.Sprintf("[DELETE /printer/network/wifi_networks/{ssid}][%d] deletePrinterNetworkWifiNetworksSsidNoContent ", 204)
}

func (o *DeletePrinterNetworkWifiNetworksSsidNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
