package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePrinterNetworkWifiNetworksSsidParams creates a new DeletePrinterNetworkWifiNetworksSsidParams object
// with the default values initialized.
func NewDeletePrinterNetworkWifiNetworksSsidParams() *DeletePrinterNetworkWifiNetworksSsidParams {
	var ()
	return &DeletePrinterNetworkWifiNetworksSsidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePrinterNetworkWifiNetworksSsidParamsWithTimeout creates a new DeletePrinterNetworkWifiNetworksSsidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePrinterNetworkWifiNetworksSsidParamsWithTimeout(timeout time.Duration) *DeletePrinterNetworkWifiNetworksSsidParams {
	var ()
	return &DeletePrinterNetworkWifiNetworksSsidParams{

		timeout: timeout,
	}
}

// NewDeletePrinterNetworkWifiNetworksSsidParamsWithContext creates a new DeletePrinterNetworkWifiNetworksSsidParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePrinterNetworkWifiNetworksSsidParamsWithContext(ctx context.Context) *DeletePrinterNetworkWifiNetworksSsidParams {
	var ()
	return &DeletePrinterNetworkWifiNetworksSsidParams{

		Context: ctx,
	}
}

// NewDeletePrinterNetworkWifiNetworksSsidParamsWithHTTPClient creates a new DeletePrinterNetworkWifiNetworksSsidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePrinterNetworkWifiNetworksSsidParamsWithHTTPClient(client *http.Client) *DeletePrinterNetworkWifiNetworksSsidParams {
	var ()
	return &DeletePrinterNetworkWifiNetworksSsidParams{
		HTTPClient: client,
	}
}

/*DeletePrinterNetworkWifiNetworksSsidParams contains all the parameters to send to the API endpoint
for the delete printer network wifi networks ssid operation typically these are written to a http.Request
*/
type DeletePrinterNetworkWifiNetworksSsidParams struct {

	/*Ssid
	  ssid of the network to forget.

	*/
	Ssid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete printer network wifi networks ssid params
func (o *DeletePrinterNetworkWifiNetworksSsidParams) WithTimeout(timeout time.Duration) *DeletePrinterNetworkWifiNetworksSsidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete printer network wifi networks ssid params
func (o *DeletePrinterNetworkWifiNetworksSsidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete printer network wifi networks ssid params
func (o *DeletePrinterNetworkWifiNetworksSsidParams) WithContext(ctx context.Context) *DeletePrinterNetworkWifiNetworksSsidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete printer network wifi networks ssid params
func (o *DeletePrinterNetworkWifiNetworksSsidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete printer network wifi networks ssid params
func (o *DeletePrinterNetworkWifiNetworksSsidParams) WithHTTPClient(client *http.Client) *DeletePrinterNetworkWifiNetworksSsidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete printer network wifi networks ssid params
func (o *DeletePrinterNetworkWifiNetworksSsidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSsid adds the ssid to the delete printer network wifi networks ssid params
func (o *DeletePrinterNetworkWifiNetworksSsidParams) WithSsid(ssid string) *DeletePrinterNetworkWifiNetworksSsidParams {
	o.SetSsid(ssid)
	return o
}

// SetSsid adds the ssid to the delete printer network wifi networks ssid params
func (o *DeletePrinterNetworkWifiNetworksSsidParams) SetSsid(ssid string) {
	o.Ssid = ssid
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePrinterNetworkWifiNetworksSsidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ssid
	if err := r.SetPathParam("ssid", o.Ssid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
