package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/kabuku/camera-to-led/ultimaker/api/models"
)

// GetPrinterNetworkWifiNetworksReader is a Reader for the GetPrinterNetworkWifiNetworks structure.
type GetPrinterNetworkWifiNetworksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrinterNetworkWifiNetworksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrinterNetworkWifiNetworksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPrinterNetworkWifiNetworksOK creates a GetPrinterNetworkWifiNetworksOK with default headers values
func NewGetPrinterNetworkWifiNetworksOK() *GetPrinterNetworkWifiNetworksOK {
	return &GetPrinterNetworkWifiNetworksOK{}
}

/*GetPrinterNetworkWifiNetworksOK handles this case with default header values.

List of network ssid'
*/
type GetPrinterNetworkWifiNetworksOK struct {
	Payload []*models.WifiNetwork
}

func (o *GetPrinterNetworkWifiNetworksOK) Error() string {
	return fmt.Sprintf("[GET /printer/network/wifi_networks][%d] getPrinterNetworkWifiNetworksOK  %+v", 200, o.Payload)
}

func (o *GetPrinterNetworkWifiNetworksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
