package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrinterNetworkWifiNetworksParams creates a new GetPrinterNetworkWifiNetworksParams object
// with the default values initialized.
func NewGetPrinterNetworkWifiNetworksParams() *GetPrinterNetworkWifiNetworksParams {

	return &GetPrinterNetworkWifiNetworksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrinterNetworkWifiNetworksParamsWithTimeout creates a new GetPrinterNetworkWifiNetworksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrinterNetworkWifiNetworksParamsWithTimeout(timeout time.Duration) *GetPrinterNetworkWifiNetworksParams {

	return &GetPrinterNetworkWifiNetworksParams{

		timeout: timeout,
	}
}

// NewGetPrinterNetworkWifiNetworksParamsWithContext creates a new GetPrinterNetworkWifiNetworksParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrinterNetworkWifiNetworksParamsWithContext(ctx context.Context) *GetPrinterNetworkWifiNetworksParams {

	return &GetPrinterNetworkWifiNetworksParams{

		Context: ctx,
	}
}

// NewGetPrinterNetworkWifiNetworksParamsWithHTTPClient creates a new GetPrinterNetworkWifiNetworksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrinterNetworkWifiNetworksParamsWithHTTPClient(client *http.Client) *GetPrinterNetworkWifiNetworksParams {

	return &GetPrinterNetworkWifiNetworksParams{
		HTTPClient: client,
	}
}

/*GetPrinterNetworkWifiNetworksParams contains all the parameters to send to the API endpoint
for the get printer network wifi networks operation typically these are written to a http.Request
*/
type GetPrinterNetworkWifiNetworksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get printer network wifi networks params
func (o *GetPrinterNetworkWifiNetworksParams) WithTimeout(timeout time.Duration) *GetPrinterNetworkWifiNetworksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get printer network wifi networks params
func (o *GetPrinterNetworkWifiNetworksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get printer network wifi networks params
func (o *GetPrinterNetworkWifiNetworksParams) WithContext(ctx context.Context) *GetPrinterNetworkWifiNetworksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get printer network wifi networks params
func (o *GetPrinterNetworkWifiNetworksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get printer network wifi networks params
func (o *GetPrinterNetworkWifiNetworksParams) WithHTTPClient(client *http.Client) *GetPrinterNetworkWifiNetworksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get printer network wifi networks params
func (o *GetPrinterNetworkWifiNetworksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrinterNetworkWifiNetworksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
