package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPrinterNetworkParams creates a new GetPrinterNetworkParams object
// with the default values initialized.
func NewGetPrinterNetworkParams() *GetPrinterNetworkParams {

	return &GetPrinterNetworkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPrinterNetworkParamsWithTimeout creates a new GetPrinterNetworkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPrinterNetworkParamsWithTimeout(timeout time.Duration) *GetPrinterNetworkParams {

	return &GetPrinterNetworkParams{

		timeout: timeout,
	}
}

// NewGetPrinterNetworkParamsWithContext creates a new GetPrinterNetworkParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPrinterNetworkParamsWithContext(ctx context.Context) *GetPrinterNetworkParams {

	return &GetPrinterNetworkParams{

		Context: ctx,
	}
}

// NewGetPrinterNetworkParamsWithHTTPClient creates a new GetPrinterNetworkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPrinterNetworkParamsWithHTTPClient(client *http.Client) *GetPrinterNetworkParams {

	return &GetPrinterNetworkParams{
		HTTPClient: client,
	}
}

/*GetPrinterNetworkParams contains all the parameters to send to the API endpoint
for the get printer network operation typically these are written to a http.Request
*/
type GetPrinterNetworkParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get printer network params
func (o *GetPrinterNetworkParams) WithTimeout(timeout time.Duration) *GetPrinterNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get printer network params
func (o *GetPrinterNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get printer network params
func (o *GetPrinterNetworkParams) WithContext(ctx context.Context) *GetPrinterNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get printer network params
func (o *GetPrinterNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get printer network params
func (o *GetPrinterNetworkParams) WithHTTPClient(client *http.Client) *GetPrinterNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get printer network params
func (o *GetPrinterNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPrinterNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
