package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutPrinterNetworkWifiNetworksSsidReader is a Reader for the PutPrinterNetworkWifiNetworksSsid structure.
type PutPrinterNetworkWifiNetworksSsidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutPrinterNetworkWifiNetworksSsidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutPrinterNetworkWifiNetworksSsidNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutPrinterNetworkWifiNetworksSsidNoContent creates a PutPrinterNetworkWifiNetworksSsidNoContent with default headers values
func NewPutPrinterNetworkWifiNetworksSsidNoContent() *PutPrinterNetworkWifiNetworksSsidNoContent {
	return &PutPrinterNetworkWifiNetworksSsidNoContent{}
}

/*PutPrinterNetworkWifiNetworksSsidNoContent handles this case with default header values.

PutPrinterNetworkWifiNetworksSsidNoContent put printer network wifi networks ssid no content
*/
type PutPrinterNetworkWifiNetworksSsidNoContent struct {
}

func (o *PutPrinterNetworkWifiNetworksSsidNoContent) Error() string {
	return fmt.Sprintf("[PUT /printer/network/wifi_networks/{ssid}][%d] putPrinterNetworkWifiNetworksSsidNoContent ", 204)
}

func (o *PutPrinterNetworkWifiNetworksSsidNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
